platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: latest

inputs:
  - name: concourse-pipeline

#outputs:
#  - name: jar-file
#    path: git-repo/target/

run:
  path: mvn
  args: ["-f", "concourse-pipeline/pom.xml", "-DskipTests=true", "package"]

