---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
- name: concourse-pipeline

run:
  path: concourse-pipeline/ci/tasks/run-unit-tests.yml
